spring:
  application:
    name: githubDailyHotSpots
llm:
  key: ${API_KEY}
  model: ${LLM_MODEL}
  url: ${LLM_URL}
mail:
  from: ${MAIL_FROM}
  to: ${MAIL_TO}
  subject: ${MAIL_SUBJECT}
  password: ${MAIL_PASSWORD}
  host: ${MAIL_HOST}
  port: ${MAIL_PORT}
  username: ${MAIL_USERNAME}

scheduler:
  cronExpression: "0 0 1 * * ?"  # 每天凌晨1点执行