spring:
  application:
    name: githubDailyHotSpots
  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    encoding: UTF-8
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    from: ${MAIL_FROM}
    ssl:
      enabled: true

llm:
  key: ${LLM_KEY}
  model: ${LLM_MODEL}
  url: ${LLM_URL}
mail:
  to: ${MAIL_TO}
  subject: ${MAIL_SUBJECT}
  from: ${MAIL_USERNAME}

scheduler:
  cronExpression: "0 3 17 * * ? "  # 每天凌晨1点执行