spring:
  application:
    name: githubDailyHotSpots
  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    encoding: UTF-8
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    from: ${MAIL_FROM}
    ssl:
      enabled: true
  datasource:
    url: jdbc:sqlite:db/database.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
    hibernate:
      ddl-auto: update

llm:
  key: ${LLM_KEY}
  model: ${LLM_MODEL}
  url: ${LLM_URL}
mail:
  to: ${MAIL_TO}
  subject: ${MAIL_SUBJECT}
  from: ${MAIL_USERNAME}

scheduler:
  cronExpression: "${SCHEDULER_CRON:0 0 8 * * ?}"