name: Gradle CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: gitea_runner

    steps:
    - name: Check Node
      run: |
        node -v
        npm -v

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # 选择一个合适的Node.js版本

    - name: Add Node.js to PATH
      run: echo "##[path]$(npm config get prefix)/bin"

    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build --no-daemon