name: Gradle CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      http_proxy: http://192.168.31.250:7890
      https_proxy: http://192.168.31.250:7890
      no_proxy: localhost,127.0.0.1,192.168.31.193

    steps:
    - name: Check Node
      run: |
        node -v
        npm -v

    - uses: zc/checkout@v4

    - name: Set up JDK 21
      uses: zc/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'
        cache-dependency-path: | # optional
          sub-project/*.gradle*
          sub-project/**/gradle-wrapper.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build --no-daemon