name: Gradle CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: gitea_runner

    steps:
    - uses: https://proxy.zhengcheng.win/https://github.com/actions/checkout@v4actions/checkout@v4

    - name: Set up JDK 21
      uses: https://proxy.zhengcheng.win/https://github.com/actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build --no-daemon