name: Gradle CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      http_proxy: http://192.168.31.250:7890
      https_proxy: http://192.168.31.250:7890
      no_proxy: localhost,127.0.0.1,192.168.31.193
      DOCKER_HOST: unix:///var/run/docker.sock

    steps:
    - name: Install Docker CLI
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh

    - uses: zc/checkout@v4

    - name: Docker build
      run: docker build -t github_daily_hotspots:latest .